### ISSUE TITLE
svs and other WSI file formats

### ISSUE THREAD

**Issue by Ru-bixcube** [labsyspharm/minerva-story#39]
In addition to cycif images typically outputted by ASALR in OME-TIF format, a popular use of Minerva is to author and share brightfield images like H&E and IHC. These are typically in .svs or other WSI file formats. Could you please add direct support for .svs and other WSI formats with built-in pyramids into Author? Thank you.

**Comment by Ru-bixcube** [comment]
https://docs.openmicroscopy.org/bio-formats/6.4.0/
https://docs.openmicroscopy.org/bio-formats/6.4.0/supported-formats.html
https://openslide.org/formats/aperio/

**Comment by jmuhlich** [comment]
When it comes time to implement this feature, please reach out to discuss the technical approach. Do not attempt to use the python-bioformats package on pypi. I use a different package in Ashlar to call the BioFormats Java API from Python but I didn't generalize that into its own standalone python package (yet). OpenSlide may also be an option, especially since it's already being used in Author.
